### ISSUE TITLE
data split list

### ISSUE THREAD

**Issue by YWCHEN-ZERO** [mrakotosaon/intrinsic_interpolations#1]
Hello!
Thanks for your excellent work!
When I read the DFAUST data set, I found that there are many similar shapes, which make it difficult to split the train and test data.
So I wonder if you can upload the data split list containing the obj files' filenames in original DFAUST data set?
Thanks

**Comment by mrakotosaon** [comment]
Hi @YWCHEN-ZERO ,
Thank you for your interest in our paper. Unfortunately I do not have this mapping anymore. 
If you wish to evaluate interpolation alone and not reconstruction, it is not always necessary to use shapes from the test set as the intermediate shapes will likely be unseen.
Please note that the dataset we used contains shapes from DFAUST but also from the SURREAL dataset. 
Best

**Comment by YWCHEN-ZERO** [comment]
How do you process the data from mesh to npy and choose them for train? I am really interested in it. Could you release the code or send the code to my email(1530459742@qq.com)?
Thanks!

**Comment by mrakotosaon** [comment]
Hi @YWCHEN-ZERO , we use the shapes from the dataset described in OperatorNet (https://arxiv.org/pdf/1904.10754.pdf). They are sampled DFAUST in a way that there are couples of poses/person that are completely unseen (please see OperatorNet for more details). The dataset also contains shapes generated from SURREAL. Then the meshes vertices are subsampled using the file enclosed to get the 1K points resolution. In our method, once we got the dataset from OperatorNet we applied a random shuffling on the training and testset separately. 
[simple_idx.zip](https://github.com/mrakotosaon/intrinsic_interpolations/files/5300424/simple_idx.zip)
Best,
