### ISSUE TITLE
The dataset link has failed

### ISSUE THREAD

**Issue by qiji77** [mrakotosaon/intrinsic_interpolations#2]
Hello，
I tried to download the dataset you provided, but I was told it was invalid.Can you provide a new link？My e-mail is diaojunqi19@mails.ucas.edu.cn.
Thank you.
Best

**Comment by mrakotosaon** [comment]
Hi @qiji77 

Thank you for letting me know about this issue. 
This new link should work: https://nuage.lix.polytechnique.fr/index.php/s/oGb7FnSqC4DYEwT/download
Best,

Marie-Julie

**Comment by qiji77** [comment]
Thank you for your reply!
