### ISSUE TITLE
Training without 1-1 correspondences

### ISSUE THREAD

**Issue by andrijazz** [mrakotosaon/intrinsic_interpolations#4]
Any chance you can post commands for running the training in unsupervised setting without 1-1 correspondences?
Also, it would be great if you can lists the preprocessing steps for dataset creation?

Thanks for the great work!

**Comment by mrakotosaon** [comment]
Hi @andrijazz 

Unfortunately I do not have the exact code for the unsupervised version online for now. However, it should be possible to reproduce from the existing code.
In particular, it would consist in:
- modifying the file train_shape_ae.py following section 4.4 and E of our paper (https://arxiv.org/pdf/2004.01661.pdf) .
- modifying train_edge_ae.py to use the output of the previously trained shape AE as ground truth for the edge length

For the dataset creation, we first subsampled a set of shapes from DFAUST and SURREAL, as many shapes from DFAUST are repetitive. We then simplify the template (and all the shapes in a consistent way from the template) using the Quadric Edge Collapse Decimation filter in meshlab. This step is not always required but it helps training faster. Finally, we saved the points of each shape into .npy files.

Please let me know if you have any question, need more details or encounter issues

**Comment by andrijazz** [comment]
Hi @mrakotosaon, thank you so much for the quick reply!

So, If I understood paper instructions correctly steps for unsupervised training would go like this:
1. Train `model_shape_ae` using tamplate `T` and `P`'s as an input using `L_recinit` loss from the paper. This should give us ordered pointclouds as an output of the network with respect to the template `T`
2. Train again `model_shape_ae` but this time we start from the model state computed in previous step ... and we use `CD` loss + `L_ereg` and `L_lapreg`. How the matrix `L` in `L_lapreg` regularization term is computed? Do you have by any chance weight parameters used for these two regularizations (`lambda_ereg`, `lambda_lapreg`)?
3. Train `model_edge_ae` but using the output of the previously trained shape AE as ground truth for the edge length
4. Train mapping networks

Is this correct?

**Comment by mrakotosaon** [comment]
1. One comment for step one: there is a possibility that the gradients dissapear if step 1 is trained for too long. So the reconstruction at this step should not be too perfect at the end of the training. 
2. L is computed from the faces of the template mesh. It can be computed as follow:
    laplacian = trimesh.smoothing.laplacian_calculation(mesh, equal_weight=True)
    laplacian = np.eye(N) - laplacian.todense()
    The weights I used were 500 for the CD loss, 5 for L_ereg and L_lapreg. However it is possible that these would differ if the implementation is not exactly the same.

The other steps are correct!

**Comment by andrijazz** [comment]
I have just one more question ...

_3. One comment for step one: there is a possibility that the gradients dissapear if step 1 is trained for too long. So the reconstruction at this step should not be too perfect at the end of the training._

Does this means that in step 3 ground truth for edge length is output of the `model_shape_ae` from step 1. or from step 2?

Thanks a lot for the help!

**Comment by mrakotosaon** [comment]
I updated my previous comment. Point 3 was actually point 1, sorry for the confusion.
The ground truth for step 3 is computed from the network trained at step 2.
