### ISSUE TITLE
Weird meshes from Surreal dataset

### ISSUE THREAD

**Issue by CLemeunier** [mrakotosaon/intrinsic_interpolations#5]
Hi, 

Thanks for the amazing work. 

Is it normal that certain meshes from the test dataset (dfaust_test.npy and surreal_test.npy) look really weird? 

Here are some snapshots:

![capture_0](https://user-images.githubusercontent.com/17198819/139431428-1e7a8783-7256-4933-a92b-7a0b525e47f2.png)
![capture_1](https://user-images.githubusercontent.com/17198819/139431431-ba2eb59e-f88a-477c-9736-857e493d53f8.png)
![capture_2](https://user-images.githubusercontent.com/17198819/139431432-2333c122-48cf-4321-a136-cbcf7eff15b7.png)
![capture_3](https://user-images.githubusercontent.com/17198819/139431434-f5f8c463-19a1-407f-89e4-3b7472ad6593.png)

Some indices corresponding to those meshes: 941, 1088, 1181, 1606.

Thanks!

**Comment by mrakotosaon** [comment]
Hi @CLemeunier 
Thank you for your interest in our work.
Our data has been generated with the parameters proposed in the code of SURREAL. Unfortunately a small part of the produced data looked distorted as you show. In practice, we assumed that these example are a minority and managed to train a model with good performance. 
Is the rest of the dataset looking better to you?

**Comment by CLemeunier** [comment]
Thanks for your answer, 

Yes, the rest of the dataset looks better. 

I might have another question: what is the total time to train the model? It seems I can't find the information. 

Thanks

**Comment by mrakotosaon** [comment]
Unfortunately I do not have exact numbers anymore. I think a few hours is enough to train each model. Training overnight would definitely be more than enough for each.  The edge and shape networks can be trained in parallel. After that, the translation networks can be trained. So one entire day should suffice for the entire pipeline. Looking at training curves might help figuring out the time to stop as well. 
Sorry I do not have the exact timings.

**Comment by CLemeunier** [comment]
Ok, no problem! 

Thanks a lot for your time
